env:
  browser: true
  es6: true
  node: true
extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  "@typescript-eslint/explicit-member-accessibility":
    accessibility: "no-public"
    overrides:
      properties: "explicit"
